### ISSUE TITLE
Umbraco 11 dashboard

### ISSUE THREAD

**Issue by ontranet** [KevinJump/Our.Umbraco.LinkedPages#15]
Seems, that Maitenance mode is added twice on Umbraco 11
<img width="1001" alt="Skærmbillede 2022-12-06 153320" src="https://user-images.githubusercontent.com/16556526/205939882-e5da49a5-ef8c-467d-a5fe-4aa84589a7f9.png">

**Comment by KevinJump** [comment]
yeah - the file is pointing to the wrong repo too 😞  

Fixed in 10.1.1 - and should be on nuget in next few minutes.

**Comment by ontranet** [comment]
Great, thanks a lot

Med venlig hilsen / Best Regards
Peter Cort Larsen

***@***.***
M  +45 42 700 100

Ontranet
Saltværksvej 187 DK-2770 Kastrup


------ Original Meddelelse ------
Fra "Kevin Jump" ***@***.***>
Til "Jumoo/Our.Umbraco.LinkedPages" 
***@***.***>
Cc "Peter Cort Larsen" ***@***.***>; "Author" 
***@***.***>
Dato 06-12-2022 15:42:49
Emne Re: [Jumoo/Our.Umbraco.LinkedPages] Umbraco 11 dashboard (Issue 
#15)
