### ISSUE TITLE
Build for Umbraco 13

### ISSUE THREAD

**Issue by tomotrepo** [KevinJump/Our.Umbraco.LinkedPages#19]
Hi, first of all thanks for the great plugin. Would it be possible to upgrade this plugin to work with Umbraco 13. Because now it doesn't, even though the marketplace says it works.

Thanks

**Comment by KevinJump** [comment]
Ahh yes, i think we put the version restriction on when we thought v13 would have the new UI. 

Removed now, and v10.0.3 is on its way to nuget

https://www.nuget.org/packages/Our.Umbraco.LinkedPages/10.0.3
